language: php

php:
  - 7.2
  
before_install:
  - travis_retry make dev-env
  - travis_retry composer dump-autoload # Dumps autoload-dev too 
  - cat vendor/composer/autoload_psr4.php

script:
  - make unit-test